apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: imported-secret
  annotations:
    crossplane.io/external-name: '/aws/lambda/crossplane-lambda-test'
spec:
  forProvider: 
    region: sa-east-1
  providerConfigRef:
    name: aws-infra-provider-config
  publishConnectionDetailsTo:
    name: imported-secret-connection