apiVersion: aws.semparar.io/v1alpha1
kind: XLambda
metadata:
  name: crossplane-lambda-test
  namespace: crossplane-system
spec:
  providerConfigName: aws-infra-provider-config
  resourceConfig:
    description: "Lambda criado via composition"
    handler: index.handler
    memorySize: 256
    region: sa-east-1
    runtime: "nodejs20.x"
    s3Bucket: flt-terraform-cloud
    s3Key: index.zip
    timeout: 10
    vpcConfig:
      securityGroupIds:
        - sg-089c4846390b31a33
      subnetIds:
        - subnet-02e13e6cae291fbb3 
        - subnet-086074f7b9d4da562
    variables:
      KEY01: Value01
      KEY02: Value02
    tags:
      Managed-by: Crossplane