apiVersion: aws.semparar.io/v1alpha1
kind: LambdaFunction
metadata:
  name: crossplane-lambda-test-01
  namespace: aws-infra
spec:
  compositionRef:
    name: composition-lambda-default
  providerConfigName: aws-infra
  resourceConfig:
    description: "Lambda criado via composition"
    handler: index.handler
    memorySize: 256
    region: sa-east-1
    role: arn:aws:iam::498638359097:role/RL_Lambda_Default
    runtime: "nodejs20.x"
    s3Bucket: flt-terraform-cloud
    s3Key: index.zip
    timeout: 15
    vpcConfig:
      securityGroupIds:
        - sg-089c4846390b31a33
      subnetIds:
        - subnet-02e13e6cae291fbb3 
        - subnet-086074f7b9d4da562
    variables:
      KEY01: Value01
      KEY02: Value02
    tags:
      Managed-by: Crossplane