apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-lambda-test
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: crossplane-lambda-test
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /aws/lambda/crossplane-lambda-test